name: comparator_sorted_map
description: A SortedMap that relies on a Comparator to sort on key, value, or a combination of both.
version: 1.0.2
homepage: https://github.com/SoftCoil/sorted_map

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
